# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

r_github_packages:
  - ./travis-tool.sh install_github knausb/vcfR
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

