# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

sudo: required

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github knausb/pinfsc50
#  - ./travis-tool.sh InstallPandoc
#  - travis_retry cabal install pandoc pandoc-citeproc  # Pandoc install using haskell (markdown parser)
#  - ./travis-tool.sh install_github sjmgarnier/viridisLite
 
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
